[package]
name = "telemetry_host"
version = "0.1.0"
authors = ["Michael Chesser"]

[dependencies]
lazy_static = "*"
mavlink = "0.4"
rocket = "0.1.6"
rocket_codegen = "0.1.6"
rocket_contrib = "0.1.6"
serde = "0.8"
serde_derive = "0.8"
